[package]
name = "riscv_trace_debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
clap = { version = "4.5.53", features = ["derive"] }
gdbstub = "0.7.8"
gdbstub_arch = "0.3.2"
goblin = "0.10.4"
num-traits = "0.2.19"
